version: '3.9'

services:
  client-dev:
    container_name: Expedition_Board_Development
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: yarn dev
    environment:
      - WATCHPACK_POLLING=true # Required for hot-reloading to work on Windows
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env

  postgres_db:
      image: postgres:13.5
      container_name: Postgres
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      volumes:
          - postgres_db:/var/lib/postgresql/data
      ports:
          - '5432:5432'
volumes:
    postgres_db:
        driver: local