version: '3.9'

services:
  client-prod:
    container_name: Expedition_Board_Production
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod

  postgres_db:
      image: postgres:13.5
      container_name: Postgres
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      volumes:
          - postgres_db:/var/lib/postgresql/data
      ports:
          - '5432:5432'
volumes:
    postgres_db:
        driver: local