version: '3.9'

services:
  client-dev:
    container_name: Expedition_Board
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: yarn dev
    environment:
      - WATCHPACK_POLLING=true # Required for hot-reloading to work on Windows
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env